---
EnableDefaultLinters: true
linters:
  ErbSafety:
    enabled: true
    better_html_config: .better-html.yml
  Rubocop:
    enabled: true
    rubocop_config:
      Rails:
        Enabled: true
      inherit_from:
        - .rubocop.yml
